services:
    broker:
        image: eclipse-mosquitto
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        ports:
            - "127.0.0.1:1883:1883"