services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1883:1883"

  django-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./src:/app
      - ./data:/app/data
    working_dir: /app
    ports:
      - "8000:8000"

  node-react:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./src/hmi_frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
