# Generated by Django 5.2.1 on 2025-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('log_data_ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('topic_config_ID', models.IntegerField()),
                ('date_logged', models.DateTimeField()),
            ],
            options={
                'db_table': 'log_data',
                'managed': False,
            },
        ),
    ]
